
MYSQL_USER = 'root'
MYSQL_PASSWORD = '1234'
MYSQL_DB = 'flask_chat_db'
MYSQL_HOST = 'localhost'

SQLALCHEMY_DATABASE_URI = f'mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = 'supersecretkey'
